/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BesoinRouteImport } from './routes/besoin'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as PortefeuilleRouteImport } from './routes/portefeuille'
import { Route as BiensIdRouteImport } from './routes/biens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BesoinRoute = BesoinRouteImport.update({
  id: '/besoin',
  path: '/besoin',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const PortefeuilleRoute = PortefeuilleRouteImport.update({
  id: '/portefeuille',
  path: '/portefeuille',
  getParentRoute: () => rootRouteImport,
} as any)
const BiensIdRoute = BiensIdRouteImport.update({
  id: '/biens/$id',
  path: '/biens/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/besoin': typeof BesoinRoute
  '/matching': typeof MatchingRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/biens/$id': typeof BiensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/besoin': typeof BesoinRoute
  '/matching': typeof MatchingRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/biens/$id': typeof BiensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/besoin': typeof BesoinRoute
  '/matching': typeof MatchingRoute
  '/portefeuille': typeof PortefeuilleRoute
  '/biens/$id': typeof BiensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/besoin' | '/matching' | '/portefeuille' | '/biens/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/besoin' | '/matching' | '/portefeuille' | '/biens/$id'
  id:
    '__root__' | '/' | '/besoin' | '/matching' | '/portefeuille' | '/biens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BesoinRoute: typeof BesoinRoute
  MatchingRoute: typeof MatchingRoute
  PortefeuilleRoute: typeof PortefeuilleRoute
  BiensIdRoute: typeof BiensIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/besoin': {
      id: '/besoin'
      path: '/besoin'
      fullPath: '/besoin'
      preLoaderRoute: typeof BesoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portefeuille': {
      id: '/portefeuille'
      path: '/portefeuille'
      fullPath: '/portefeuille'
      preLoaderRoute: typeof PortefeuilleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biens/$id': {
      id: '/biens/$id'
      path: '/biens/$id'
      fullPath: '/biens/$id'
      preLoaderRoute: typeof BiensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BesoinRoute: BesoinRoute,
  MatchingRoute: MatchingRoute,
  PortefeuilleRoute: PortefeuilleRoute,
  BiensIdRoute: BiensIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
